### ISSUE TITLE
Downgrade to react 17 to match the version current GraphiQL is using

### ISSUE THREAD

**Issue by matijagaspar** [nearform/mercurius-federation-info-graphiql-plugin#121]
This plugin is using React 18 but only in development, in it's built state is using the react version [supplied by GraphiQL which is [currently 17.0.2](https://github.com/graphql/graphiql/blob/main/packages/graphiql/package.json#L90) .This can be a source of issues, but there is also many warnings when running `npm install`

**Comment by simoneb** [comment]
we also need find a way to prevent dependabot from upgrading it

**Comment by matijagaspar** [comment]
> we also need find a way to prevent dependabot from upgrading it

Good point, looking into it
