### ISSUE TITLE
Update table view layout according to design

### ISSUE THREAD

**Issue by codeflyer** [nearform/mercurius-federation-info-graphiql-plugin#82]
A new design was made to improve the usability of the plugin.

https://www.figma.com/file/Qf8hgYpM5kUzItgVdesLbu/Federation-info?node-id=106%3A13535&t=XpsGV5ozdDJuoJoh-0

![Screenshot 2022-11-24 at 11 47 57](https://user-images.githubusercontent.com/2649145/203766753-0057bef2-fcf7-4174-b6d2-fcfa1da90c88.png)

The design is based on material UI that should be integrated in the project.

The view is initially integrated in the current `tab` view.

This part is not required, it will be covered in a separate task

![Screenshot 2022-11-24 at 11 58 15](https://user-images.githubusercontent.com/2649145/203767563-16d5037c-960e-444b-a68a-64695fdcec28.png)

The table should open with the first level opened and the lines can be opened/closed clicking on the specific `>` icon.

```
├─ Queries
│   ├─ me
│   └─ userList
├─ Mutations
│   ├─ updateUser
│   └─ doSomething
├─ Subscriptions
└─ Types
    ├─ User
    ├─ Country
    ├─ Address
    └─ Post
```

The open/close configuration should be stored to allow the user to keep the layout when switching between tabs. (Context? LocalStorage?)

**Comment by simoneb** [comment]
Design looks amazing!

**Comment by andreaforni** [comment]
@simoneb, I picked this ticket yesterday's morning, I'm working on it
