### ISSUE TITLE
Update tree view layout according to design

### ISSUE THREAD

**Issue by codeflyer** [nearform/mercurius-federation-info-graphiql-plugin#83]
A new design was made to improve the usability of the plugin.

https://www.figma.com/file/Qf8hgYpM5kUzItgVdesLbu/Federation-info?node-id=106%3A13535&t=XpsGV5ozdDJuoJoh-0

![Screenshot 2022-11-24 at 11 47 57 copy](https://user-images.githubusercontent.com/2649145/203769608-dacf7ee2-f360-4588-9f1d-6db2b4b65b46.png)

The design is based on material UI that should be integrated in the project.

The view is initially integrated in the current `tab` view.

This part is not required, it will be covered in a separate task
![Screenshot 2022-11-24 at 12 08 51](https://user-images.githubusercontent.com/2649145/203769798-872bf279-4183-4ac8-9721-5148515287f2.png)

The `tree` should open with all the entries closed and only the service list will be visible, the specific service can be opened/closed by clicking on service name, and all the children can be opened/closed clicking on the specific icon.

```
├─ Service 1
├─ Service 2
├─ Service 3
└─ Service 4
```

The open/close configuration should be stored to allow the user to keep the layout when switching between tabs. (Context? LocalStorage?)

**Comment by simoneb** [comment]
Thanks @andreaforni . Let's keep an eye on that issue and if nobody picks it up we can work on that too, but not before we have a first working implementation for this issue.

**Comment by andreaforni** [comment]
> Thanks @andreaforni . Let's keep an eye on that issue and if nobody picks it up we can work on that too, but not before we have a first working implementation for this issue.

Sure! It's a marginal thing, better to focus and close our redesign first.

**Comment by andreaforni** [comment]
# Tree View
To implement the Service trees, I used the MUI's `<TreeView>` component. I tried to match the design provided, but I was not able to find a working implementation of the dashed branches:

<img width="347" alt="Federation_info_–_Figma" src="https://user-images.githubusercontent.com/1233582/206205879-ec73d244-c184-4602-9353-b95dab3fe77d.png">

I tried the [suggested example in the official doc](https://mui.com/material-ui/react-tree-view/#custom-icons-border-and-animation), but the vertical branch is too long, and I cannot implement the corner:

<img width="425" alt="Federation_info_–_Figma-2" src="https://user-images.githubusercontent.com/1233582/206208114-1d11fbc6-116a-4fef-b2c4-77da8eed4642.png">

This is the MUI example:
![Tree_view_React_component_-_Material_UI](https://user-images.githubusercontent.com/1233582/206207742-ba05e708-6e65-48a4-91d5-74d954f43610.png)

With @matijagaspar we found a better-looking solution (using absolute positioned `:before` and `:after` pseudo-elements) but sadly, was not compatible with the collapse animation used by the tree. As you can see in the following video, the vertical branch does not animate and appears when the transition ends:

https://user-images.githubusercontent.com/1233582/206209060-4bbd7035-3674-4a58-bcf5-846ad50045e2.mov


**Action:**Create an issue to keep track of the problem and consider using other tree libraries or writing the component from scratch.

**Comment by simoneb** [comment]
yes we're good without pixel perfection for now (and possibly the future). let's make it work then we make it also nice
